from typing import Any, Optional

from ._group import GenericGroup


class Group(GenericGroup):
    """A group with user specified elements."""

    def __init__(
        self,
        elements: Optional[list[Any]] = None,
        multiplication_table: Optional[list[list[int]]] = None,
        head_group: Optional["Group"] = None,
        head_group_index: Optional[set[int]] = None,
    ):
        """
        .. rubric:: Constructor

        Notes
        -----

        To construct a head group, provide `elements` and
        `multiplication_table`. To construct a subgroup, provide `head_group` and
        `head_group_index` and optionally, `elements`.

        Examples
        --------

        Construct a head group with 4 elements and the following multiplication table:

        .. code-block:: python

            elements = ["e", "a", "b", "c"]

            multiplication_table = [
                [0, 1, 2, 3],  # e * e = e, e * a = a, e * b = b, e * c = c
                [1, 0, 3, 2],  # a * e = a, a * a = e, a * b = c, a * c = b
                [2, 3, 0, 1],  # b * e = b, b * a = c, b * b = e, b * c = a
                [3, 2, 1, 0],  # c * e = c, c * a = b, c * b = a, c * c = e
            ]

            group = Group(
                elements=elements,
                multiplication_table=multiplication_table,
            )

        Construct a subgroup of the above group with head group indices {0, 2},
        corresponding to the elements ["e", "b"].

        .. code-block:: python

            subgroup = group.make_subgroup(
                head_group_indices={0, 2}
            )

        If the original group represents a factor group, then the subgroup can be
        represented as a subgroup of the factor group with the same head group indices,
        but with different `elements`, for instance `["e", "b'"]` where `b'` is a
        different member of the same coset as `b` in the original group.

        .. code-block:: python

            subgroup = group.make_subgroup(
                head_group_indices={0, 2},
                elements=["e", "b'"],
            )


        Parameters
        ----------
        elements: Optional[list[typing.Any]] = None
            The group elements. The type of the elements is not specified, but they
            should be compatible with the multiplication table. The first element
            must be the identity element.

        multiplication_table: Optional[list[list[int]]] = None
            The multiplication table element
            ``multiplication_table[i][j] == k`` represents that
            ``np.allclose(elements[k], elements[i] @ elements[j]) == True``.

            The multiplication table must be square, represent a closed
            group, and be consistent with having identity operation as the
            first element.

        head_group: Optional[GenericGroup] = None
            The head group if this is a subgroup, else None. If None, then
            this is a head group.
        head_group_index: Optional[set[int]] = None
            Indices of elements in the head group (which may or may not be
            `self`) to include in a subgroup. Only used if `head_group` is
            not None.
        """
        super().__init__(
            multiplication_table=multiplication_table,
            head_group=head_group,
            head_group_index=head_group_index,
        )

        self.elements = elements
        """list[Any]: The group elements."""

    def make_subgroup(
        self,
        head_group_index: set[int],
        elements: Optional[list[Any]] = None,
    ) -> "Group":
        """Make a subgroup of this group with the specified head group indices.

        Make a subgroup

        Parameters
        ----------
        head_group_index: set[int]
            Indices of elements in the head group (which may or may not be
            `self`) to include in the subgroup.
        elements: Optional[list[libcasm.xtal.SymOp]] = None
            If not None, use the provided elements for subgroup elements list.
            This allows using a factor group for the head group and representing
            a subgroup of the entire group as a subgroup of the factor group.

        Returns
        -------
        subgroup: Group
            The subgroup generated by the specified head group elements.
        """
        return Group(
            elements=elements,
            head_group=self,
            head_group_index=head_group_index,
        )
