name: Build wheels

on:
  push:
  pull_request:
  schedule:
    - cron: '0 12 * * 0'

jobs:
  build_wheels_linux_x86_64:
    name: Build x86_64 wheels on ubuntu-24.04
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.0.1
        env:
          CIBW_ARCHS_LINUX: x86_64

      - uses: actions/upload-artifact@v4
        with:
          name: dist_linux_x86_64
          path: ./wheelhouse/*.whl

  build_wheels_linux_aarch64:
    name: Build aarch64 wheels on ubuntu-24.04
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.0.1
        env:
          CIBW_ARCHS_LINUX: aarch64

      - uses: actions/upload-artifact@v4
        with:
          name: dist_linux_aarch64
          path: ./wheelhouse/*.whl

  build_wheels_macos13_x86_64:
    name: Build x86_64 wheels on macos-13
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.0.1
        env:
          CIBW_ARCHS_MACOS: x86_64

      - uses: actions/upload-artifact@v4
        with:
          name: dist_macos13_x86_64
          path: ./wheelhouse/*.whl

  build_wheels_macos15_arm64:
    name: Build arm64 wheels on macos-15
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.0.1
        env:
          CIBW_ARCHS_MACOS: arm64

      - uses: actions/upload-artifact@v4
        with:
          name: dist_macos15_arm64
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build sdist
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Set up requirements and configuration variables
        run: |
          sudo apt-get update
          sudo apt-get install build-essential cmake
          pip install --upgrade pip wheel build
          git submodule update --init --recursive

      - name: make
        shell: bash
        run: |
          python -m build

      - name: upload sdist
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dist_sdist
          path: dist/*.tar.gz
