name: Testing build on macos-latest

on:
  push:
  pull_request:
  schedule:
    - cron: '0 12 * * 0'

jobs:
  build:
    runs-on: macOS-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Set up requirements & configuration variables
        run: |
          brew update
          brew install cmake
          pip install --upgrade pip wheel build
          pip install -r test_requirements.txt

      - name: make
        shell: bash
        run: |
          python -m build

      - name: install
        shell: bash
        run: |
          pip install dist/*.whl

      - name: make test
        shell: bash
        run: |
          export CASM_PREFIX=$(python -m libcasm.casmglobal --prefix)
          python -m pytest -rsap python/tests

      - name: upload libcasm-configuration-macos-latest-x86_64-dist
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: libcasm-configuration-macos-latest-x86_64-dist
          path: dist
