name: Testing on macos-latest

on:
  push:
  pull_request:
  schedule:
    - cron: '0 12 * * 0'

jobs:
  build:
    runs-on: macOS-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Set up requirements & configuration variables
        run: |
          brew update
          brew install cmake
          pip install --upgrade pip wheel
          pip install -r test_requirements.txt

      - name: make
        shell: bash
        run: |
          pip install .

      - name: make test
        shell: bash
        run: |
          export CASM_PREFIX=$(python -m libcasm.casmglobal --prefix)
          python -m pytest -rsap python/tests
